plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'org.moddingx'
java.toolchain.languageVersion = JavaLanguageVersion.of(25)

repositories {
    mavenCentral()
}

dependencies {
    implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
    implementation 'org.apache.commons:commons-text:1.15.0'
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'org.jsoup:jsoup:1.22.1'
    implementation 'org.commonmark:commonmark:0.27.0'
    implementation 'org.commonmark:commonmark-ext-gfm-tables:0.27.0'
}

var fatJar = tasks.register('fatjar', Jar) { task ->
    archiveClassifier = 'fatjar'
    manifest = tasks.named('jar', Jar).get().manifest
    with tasks.named('jar', Jar).get()

    configurations.runtimeClasspath.each { dep ->
        task.from(project.zipTree(dep)) {
            exclude 'META-INF/MANIFEST.MF', 'META-INF/INDEX.LIST'
            exclude 'module-info.class', 'META-INF/versions/*/module-info.class'
            exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'META-INF/SIG-*'
            exclude 'META-INF/README*', 'META-INF/LICENSE*', 'META-INF/NOTICE*'
            exclude 'META-INF/readme*', 'META-INF/license*', 'META-INF/notice*'
            duplicatesStrategy DuplicatesStrategy.FAIL
        }
        task.from(project.zipTree(dep)) {
            include 'META-INF', 'META-INF/**', 'module-info.class'
            into "META-INF/libraries/${dep.name.replaceAll('\\.jar$', '')}/"
            duplicatesStrategy DuplicatesStrategy.FAIL
        }
    }
}

var sourcesJar = tasks.register('sourcesJar', Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
    dependsOn tasks.named('classes')
}

tasks.named('build').configure { task ->
    task.dependsOn fatJar
    task.dependsOn sourcesJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
            pom {
                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "https://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
            }
        }
    }
    repositories {
        maven {
            name 'moddingx'
            url 'https://maven.moddingx.org/release'
            credentials(PasswordCredentials)
        }
    }
}
